name: CI workflow

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: module-5-testing/lab
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install
        run: |
          npm ci
          npm install @rollup/rollup-linux-x64-gnu --save-optional
      - name: Tests
        run: npm test
